### ISSUE TITLE
UserDiscriminator, error getting form type : "PGX\UserBundle\Form\Type\RegistrationUserOneFormType" not found

### ISSUE THREAD

**Issue by senol1** [PUGX/PUGXMultiUserBundle#100]
Pleaze help me.

**Comment by giorrrgio** [comment]
Please help us with some more info :-)
There's a typo in the FQN you reported "PGX\UserBundle\Form\Type\RegistrationUserOneFormType" should be "PUGX\UserBundle\Form\Type\RegistrationUserOneFormType" check your code.

**Comment by senol1** [comment]
Don't understand 
I feel he wants me to create a "form type" for the user
What is really the problem here
Maybe I have not installed

**this prevents me from continuing**
