### ISSUE TITLE
How to do routing management?

### ISSUE THREAD

**Issue by napestershine** [PUGX/PUGXMultiUserBundle#107]
Hi

**My app/config/routing.yml looks like**

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /tadmin

web:
    resource: "@WebBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

**And my WebBundle/Resources/config/routing.yml is:**

user_one_registration:
    pattern:  /register/user-one
    defaults: { _controller: WebBundle:RegistrationUserOne:register }

user_two_registration:
    pattern:  /register/user-two
    defaults: { _controller: WebBundle:RegistrationUserTwo:register }

web_homepage:
    path:     /
    defaults: { _controller: WebBundle:Default:index }

Am I correct or wrong?

**Comment by fcpauldiaz** [comment]
I import each resource of FOSUserBundle one by one instead of the all.xml but it should work the same. Are you getting errors?
