### ISSUE TITLE
Exception events not fired

### ISSUE THREAD

**Issue by mcbuckets** [PUGX/PUGXMultiUserBundle#116]
Does anyone have or had issue with exceptions rendering as html on /login page with FOSUserBundle. For example, Bad credentials error is displayed as html alongside login form with response 200.
From Debug toolbar it seems that kernel exception events are not being fired and login page returns html exception.

**Comment by garak** [comment]
This is not related to this bundle, but to Symfony authentication system. The exception is fired, but is caught.
