### ISSUE TITLE
Error after composer install today

### ISSUE THREAD

**Issue by rtoledof** [PUGX/PUGXMultiUserBundle#124]
After made the composer install and update the FosUser bundle I have this error.

Type error: Argument 1 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must implement interface FOS\UserBundle\Util\PasswordUpdaterInterface, instance of Symfony\Component\Security\Core\Encoder\EncoderFactory given, called in /home/rolando/Public/new_gateway/vendor/pugx/multi-user-bundle/PUGX/MultiUserBundle/Doctrine/UserManager.php on line 47

In composer I have 

 "friendsofsymfony/user-bundle": "2.0.*@dev",
 "pugx/multi-user-bundle": "3.0.*@dev",

**Comment by garak** [comment]
I see a lot of other BCs.
I'm afraid that you need to stick FOSUserBundle to a previous commit (or a previous tag)

**Comment by rtoledof** [comment]
In you repository which tag I should be use??

**Comment by garak** [comment]
I was talking about FOSUserbundle's tags. Here there's no tag (not event a commit) compatible with such recent BCs

**Comment by rtoledof** [comment]
Ok I already use the commit was working before and it's working now. Thanks
