### ISSUE TITLE
assetic:dump crashes with pugXMultiUserBundle

### ISSUE THREAD

**Issue by Organicdareal** [PUGX/PUGXMultiUserBundle#125]
I was ok on my dev server, and i tried to deploy with capifony, as usual.  It crashes every time on assetic:dump command, with this log : 

`[Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must implement interface
  FOS\UserBundle\Util\PasswordUpdaterInterface, instance of Symfony\Component\Security\Core\Encoder\EncoderFactory given,
  called in /var/www/MIP/vendor/pugx/multi-user-bundle/PUGX/MultiUserBundle/Doctrine/UserManager.php on line 47 and define
  d
`

Then i tried to assetic:dump on my dev server, and now i'm unable to do anything, cache:clear crashes with the same log error.

I didn't touch anything related to the bundle, so what happened ? Did the bundle updated and is no longer compatible ? I work with Symfony 2.7

Thanks

**Comment by garak** [comment]
See #124

**Comment by Organicdareal** [comment]
Hi, thanks for your answer, it seems like the way to go.
I tried to force
`
        "friendsofsymfony/user-bundle" : "2.0.0",
        "pugx/multi-user-bundle": "3.0.*@dev",`

in my composer.json, but i still got the error. What am i doing wrong ?

**Comment by garak** [comment]
There is no stable `2.0` release for FOSUserBundle now. You can stick to `v2.0.0-alpha3` (for FOS, *not* for this bundle)
I'm closing this.

**Comment by Organicdareal** [comment]
That's what i get when i use alpha3 version : 

`
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "pugx_user.manager.orm_user_manager" has a dependency on a non-existent service "fos_user.object_manager".


Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception


  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:


    [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]

    The service "pugx_user.manager.orm_user_manager" has a dependency on a non-existent service "fos_user.object_m
  anager".`

Sorry to bother you...

**Comment by garak** [comment]
See #98

**Comment by Organicdareal** [comment]
> In PUGX\MultiUserBundle\Resources\config\orm.yml replace "@fos_user.entity_manager" by "@fos_user.object_manager"
In app\config\config.yml add services: fos_user.doctrine_registry: alias: doctrine

Those modifications are already applied on my files...

**Comment by Organicdareal** [comment]
Thanks for your help
