### ISSUE TITLE
Update FriendsOfSymfony/FOSUserBundle

### ISSUE THREAD

**Issue by Thibault34** [PUGX/PUGXMultiUserBundle#128]
Hello,
I have a problem, after composer update, FriendsOfSymfony/FOSUserBundle is updated.

I have now a error :
Argument 1 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must implement interface FOS\UserBundle\Util\PasswordUpdaterInterface, instance of Symfony\Component\Security\Core\Encoder\EncoderFactory given, called in C:\wamp\apps\europemat.com\vendor\pugx\multi-user-bundle\PUGX\MultiUserBundle\Doctrine\UserManager.php on line 47 and defined

Can you help me please ?

**Comment by garak** [comment]
See #124
