### ISSUE TITLE
Error after composer update

### ISSUE THREAD

**Issue by mathiasmondofute** [PUGX/PUGXMultiUserBundle#131]
Hello, I just did an update of fosuser via "composer update " in my Symfony2 project and since then I have this error occurred, it could someone get me out of this problem? Thank you in advance.

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must implement interface FOS\UserBundle\Util\PasswordUpdaterInterface, instance of Symfony\Component\Security\Core\Encoder\EncoderFactory given, called in /home/mondofutedev.com/domains/crm-preprod.mondofutedev.com/public_html/vendor/pugx/multi-user-bundle/PUGX/MultiUserBundle/Doctrine/UserManager.php on line 47 and defined" at /home/mondofutedev.com/domains/crm-preprod.mondofutedev.com/public_html/vendor/friendsofsymfony/user-bundle/Doctrine/UserManager.php line 46 {"exception":"object"} []

**Comment by garak** [comment]
See #124
