### ISSUE TITLE
Missing service after composer update

### ISSUE THREAD

**Issue by MedardI** [PUGX/PUGXMultiUserBundle#138]
Whilst attempting to do a composer update today, I am getting this error:

The service "pugx_user.manager.orm_user_manager" has a dependency on a non-existent service "fos_user.util.password_updater". 

It seems like the following services are missing: 
@fos_user.util.password_updater
@fos_user.util.canonical_fields_updater
@fos_user.object_manager

Any idea why this is happening?

Here are my configs: 

"friendsofsymfony/user-bundle": "~2.0@dev",
"pugx/multi-user-bundle": "3.0.*@dev",

and Symfony : 
"symfony/symfony": "2.8.*"

**Comment by garak** [comment]
If you miss that services, you're not up to date with latest FOSUserBundle
