### ISSUE TITLE
pugx_user.manager.orm_user_manager" has a dependency on a non-existent service "fos_user.util.password_updater"

### ISSUE THREAD

**Issue by houssemkachouti** [PUGX/PUGXMultiUserBundle#141]
After i install PUGX and just after i add  "new PUGX\MultiUserBundle\PUGXMultiUserBundle()," to the appKernel.php i got this problem 
i m using 
        "friendsofsymfony/user-bundle": "2.0.0-alpha2",

**Comment by garak** [comment]
See #98
