### ISSUE TITLE
Problem with listener

### ISSUE THREAD

**Issue by padalec** [PUGX/PUGXMultiUserBundle#146]
Hi there
I found a little bug in https://github.com/PUGX/PUGXMultiUserBundle/blob/master/Controller/RegistrationManager.php#L60
you return only result response when result is RedirectRespons but right now I use JsonRespons in my listener and my response isn't returned.
This fix this issues:
`        if ($result instanceof Response) {
            return $result;
        }`

**Comment by rosoarv** [comment]
template from
        `# app/config/config.yml
        ...
        registration:
          form: 
            type: Acme\UserBundle\Form\Type\RegistrationUserOneFormType
            name: fos_user_registration_form
            validation_groups:  [Registration, Default]
          template: AcmeUserBundle:Registration:user_one.form.html.twig
        ...`
 is not loaded after adding the fix.

**Comment by bplaa-yai** [comment]
Hi,
I think this commit is the cause of issue #151 
If I'm not wrong, the manager's logic is to return FOSUB's response only in case of success (in which case it's an instance of RedirectResponse), else it returns its own response with the customized form and so on.
By returning FOSUB's response if it's an instance of Response (which it always is), the manager never gets an opportunity to return its own response.

**Comment by bplaa-yai** [comment]
@garak any thoughts on this ?

**Comment by garak** [comment]
It's hard to tell for me, since I don't use this bundle since a while

**Comment by ldesmeules** [comment]
I confirm this commit is the cause of issue #151 
I need to reverse changes to return the template in config

**Comment by Ardinis** [comment]
I confirm too.
