### ISSUE TITLE
supporting symfony 3.4

### ISSUE THREAD

**Issue by nmihaylov** [PUGX/PUGXMultiUserBundle#159]
Hi There,

As long I as saw into composer.json Symfony version 3.0 is supported. Is there any particular reason for not supporting Symfony 3.4 as it should have backwards compability with 3.0 and all should be ok?

If symfony 3.4 is not supported on purpose do you have an idea when it will be added as available option?

Regards,
Niki

**Comment by garak** [comment]
I guess it will never happen. This bundle is almost abandoned
