### ISSUE TITLE
Support for Symfony 4

### ISSUE THREAD

**Issue by akoh-victor** [PUGX/PUGXMultiUserBundle#160]
How can i install  PUGXUserBundle to symfony 4 ? 

i get error 
` Problem 1
    - Installation request for pugx/multi-user-bundle  dev-master -> satisfiable by pugx/multi-user-bundle[dev-master].
    - pugx/multi-user-bundle dev-master requires symfony/framework-bundle ^2.7|^3.0 `

how can i solve this ?

**Comment by garak** [comment]
You cannot. There's no plan to support Symfony 4 in this bundle, nor any plan to keep it up to date.

**Comment by akoh-victor** [comment]
wow ! thank you at least for your reply. Do you recommend any other bundle for a replacement ?

**Comment by garak** [comment]
I recommend to avoid FOSUserBundle and similar bundles.
Just build your own User using basic Symfony docs about authentication and authorization

**Comment by akoh-victor** [comment]
Many thanks i think is high time i do that
