### ISSUE TITLE
Installation with symfony 2.4

### ISSUE THREAD

**Issue by jcdop** [PUGX/PUGXMultiUserBundle#60]
I'm trying to install PUGXMultiUserBundle, but  I get the following message when i do a composer.phar update

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: friendsofsymfony/user-bundle[2.0.x-dev, 1.3.x-dev].
    - Can only install one of: friendsofsymfony/user-bundle[2.0.x-dev, 1.3.x-dev].
    - pugx/multi-user-bundle dev-master requires friendsofsymfony/user-bundle 2.0.x-dev@dev -> satisfiable by friendsofsymfony/user-bundle[2.0.x-dev].
    - Installation request for pugx/multi-user-bundle dev-master -> satisfiable by pugx/multi-user-bundle[dev-master].
    - Installation request for friendsofsymfony/user-bundle 1.3.x-dev -> satisfiable by friendsofsymfony/user-bundle[1.3.x-dev].

composer.json 

 "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "~2.4",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "symfony/process": "2.3.*@dev",
...
 "friendsofsymfony/user-bundle": "2.0.@dev",
"pugx/multi-user-bundle": "dev-master",

...

**Comment by garak** [comment]
Do not use "dev-master", use "3.0.*@dev" instead.
Anyway, Symfony 2.4 is out of support, so I'm closing this. Feel free to re-open.
