### ISSUE TITLE
Hard FOSUserBundle version constraint in 1.4.1

### ISSUE THREAD

**Issue by kix** [PUGX/PUGXMultiUserBundle#69]
[Current PUGXMultiUserBundle 1.4.1](https://github.com/PUGX/PUGXMultiUserBundle/blob/v1.4.1/composer.json) ([commit](https://github.com/PUGX/PUGXMultiUserBundle/blob/8407f503d255c89695dc1ecfc94a3002efdf21db/composer.json#L19)) has a hard dependency on FOSUserBundle 1.3.1. However, that's not very SemVer`ic and it causes compatibility problems:

```
friendsofsymfony/user-bundle v1.3.1 requires symfony/security-bundle >=2.1,<2.3-dev
```

If there are no good reasons to use `1.3.1`, maybe the dependency could be weakened?

**Comment by garak** [comment]
Fixed in `v2.0.0`
