### ISSUE TITLE
Question about multiusering

### ISSUE THREAD

**Issue by gyrocopter** [PUGX/PUGXMultiUserBundle#87]
Hello, guys! Yep, obviously, there is awesome bundle for multiusering! So, i wanna use it and i have a few question. Please, give me answers on them:

I have bundles:

```
Site1Bundle // site1.com
Site2Bundle // site2.com
...
SiteNBundle // siteN.com
```
(each bundle for each site)

For each of this bundles (sites) i need to create single user tables, entities, etc. Can i do it on their's folders or i should do entities, registration controllers for each of this sites just in UserBundle (with UserOne, UserTwo, etc.)?

And how i can render registration form in Site1Bundle for UserOne, for example?

**Comment by gyrocopter** [comment]
Related on #89

**Comment by giorrrgio** [comment]
Let's leave only this open

**Comment by gyrocopter** [comment]
@giorrrgio In this issue doesn't visible the trouble about just one field on user tables

**Comment by leopro** [comment]
So @gyrocopter which is the question?

**Comment by gyrocopter** [comment]
@leopro, @giorrrgio My question is: 

I use this plugin, because i have in my Symfony project a few web-sites. For each web-site i want to make single User Class, single registration form, ..., and single table in database. 
So, i installed plugin, did whole actions by documentation, and didn't get what i needed. After registration all users (from user_one, user_two) saves to user (default) table, and they different just by type. And in tables user_one, user_two, ... i see just one field, it is - id.

But i need single table with single users for each site. For example: i want to register on all sites, and i can't do it, because all users stores on ONE table.

I think, it was more completely :) (and sorry for my english)

**Comment by leopro** [comment]
The purpose of this bundle is to have a sub-typing of the user.
Then you can register, login and so on using fosub.
I don't think you can use it for your needs.

**Comment by gyrocopter** [comment]
@leopro What is sub-types of user? Sub-typing it is synonym of groups/roles (default) ?

I see, that user_one table has just one field and this field is foreign key, relates on main table. 

Sorry, i am not newbie and I can't understand idea of your Bundle, if for each entity doesn't creates single table with single data...

**Comment by gyrocopter** [comment]
"Thanks" for responses, guys. I am very disappointed.
