### ISSUE TITLE
Why user_one and user_two tables has just one field (id) ??

### ISSUE THREAD

**Issue by gyrocopter** [PUGX/PUGXMultiUserBundle#89]
Or i do smth wrong? I did it by the documentation. Can i save user with different type just on another table? Not in users table

**Comment by leopro** [comment]
Sorry I'm not understanding. Which is your expectation?

**Comment by gyrocopter** [comment]
@leopro My expectation was: for each user class creates single table (user_one, user_two, etc.).

So, why i wanna use this plugin? I have in my Symfony project many sites (OneSite, TwoSite, ...). For each of them i want single table for users. If i will not do it, one user can't register on all of my sites.

**Comment by giorrrgio** [comment]
@gyrocopter this is the third issue you open on the same subject. Leaving only one open.

**Comment by gyrocopter** [comment]
@giorrrgio Yea, thanks for responses! I closed both and commented about relation on this issue.
