### ISSUE TITLE
FOSUser dependency issue

### ISSUE THREAD

**Issue by nsoftproject** [PUGX/PUGXMultiUserBundle#98]
The service "pugx_user.manager.orm_user_manager" has a dependency on a non-existent service "fos_user.entity_manager"

**Comment by rvntone** [comment]
I have the same problem, the last update of fos_user broke this bundle.

**Comment by Coyzz** [comment]
Same issue ! :(

**Comment by GdotBdot** [comment]
+1

**Comment by kevin4486** [comment]
+1, fos_user.entity_manager has been renamed fos_user.object_manager

**Comment by kevin4486** [comment]
For those with the same problem, here is a short term solution (tested with symfony 2.6):
- In PUGX\MultiUserBundle\Resources\config\orm.yml replace "@fos_user.entity_manager" by "@fos_user.object_manager"
- In app\config\config.yml add 
services:
    fos_user.doctrine_registry:
        alias: doctrine

Waiting for an official !

**Comment by garak** [comment]
Thanks @kevin4486 for your suggestion.
Please not that the alias is still needed, since it depends on a bug in Symfony and not in this bundle
